### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by zilaijuand** [plant720/Easy353#1]
Hi
  I have been experiencing this error while using the easySFS and I have no idea how to fix it.
  Thanks, Looking forward to your reply.

easy353.py -1 HKXS02_R1.fq.gz -2 HKXS02_R2.fq.gz -o out_try -r ~/software/353_ref_Gesneriaceae/353gene/ 

usage: easy353.py [options]
easy353.py: error: unrecognized arguments: -1 HKXS02_R1.fq.gz -2 HKXS02_R2.fq.gz -o out_try -r /public/home/lifengrong/software/353_ref_Gesneriaceae/353gene/

**Comment by plant720** [comment]
The reason for the error is that the code for the parameter parsing part has been commented out. Now this bug has been fixed. You can download the latest version of Easy353.

**Comment by zilaijuand** [comment]
Thanks!
