### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by zilaijuand** [plant720/Easy353#2]
您好：
  我在运行软件的时候，遇到了以下问题，麻烦向您请教一下如何解决，谢谢！

**command line:**
easy353.py -1 E100071774_L01_UDB4_NT01_R1.fq.gz -2 E100071774_L01_UDB4_NT01_R2.fq.gz -r ~/software/Easy353-master/353_ref_Gesneriaceae/353gene/ -o E100071774_L01_UDB4_NT01_gzout_353 -k1 31 -k2 41 -t1 32 -t2 32
**error message：**
usage: easy353.py [options]
easy353.py: error: unrecognized arguments: -k1 31 -k2 41 -t1 32 -t2 32

**command line:**
easy353.py -1 E100071770_L01_UDB103_DMDT01_R1.fq.gz -2 E100071770_L01_UDB103_DMDT01_R2.fq.gz -r ~/software/Easy353-master/353_ref_Gesneriaceae/353gene/ -o E100071770_L01_UDB103_DMDT01_gzout_353 -t1 32 -t2 32
**error message：**
usage: easy353.py [options]
easy353.py: error: unrecognized arguments: -t1 32 -t2 32

**Comment by plant720** [comment]
软件的部分参数根据实际意义进行了修改，-k1 31 -k2 41 -t1 32 -t2 32应该换成 -fk 31 -ak 41 -ft 32 -at 32. 其中fk表示过滤时的kmer设置，ak表示拼接时的kmer设置；ft和at则分别是过滤和拼接时所用的线程数

**Comment by zilaijuand** [comment]
非常感谢！
