### ISSUE TITLE
Assembly not working properly with the command line version

### ISSUE THREAD

**Issue by weitkaemper** [plant720/Easy353#4]
Thank you very much for your excellent work! 
I am trying to assemble reads from Angiosperms353 sequences.
I am facing the following issue: After using build_database.py following the pattern in the docs,  I run easy353.py. However, while it hashes the same (number of) sequences as from the GUI, it then proceeds to align only a very small number of "genes". Upon checking the assembly output, I discover that Easy353 attempted to assemble against the individuals from the reference library rather than the 353 genes, leading to nonsense output. 

Using the GUI, I enter the family name as the taxon for fetching the reference genes, and then recover essentially all gene regions, which is great. 
So the issue only seems to affect the command line version.
However, I have many individuals, so I do need to use the command line version to allow for scripting. 
I have tested this under both Ubuntu Linux and MS Windows, with the same outcome.
Any help would be appreciated!

**Comment by weitkaemper** [comment]
Note: I have only tested the GUI under Windows and the command line on both Windows and Linux.

**Comment by weitkaemper** [comment]
It seems the issue is resolved by specifying the subdirectory 353gene of the reference library. Maybe it would be helpful to change the sample call on the github landing page to reflect this though?

**Comment by plant720** [comment]
> It seems the issue is resolved by specifying the subdirectory 353gene of the reference library. Maybe it would be helpful to change the sample call on the github landing page to reflect this though?

Thank you for your suggestion! We have now updated the sample call on the GitHub landing page to reflect specifying the subdirectory "353gene" of the reference library. Your feedback is greatly appreciated.
