### ISSUE TITLE
Easy353 cant't use more than one thread for filtering in Windows GUI version

### ISSUE THREAD

**Issue by suLuyi** [plant720/Easy353#5]
In Easys353 Windows GUI, if the filtering threads is setting to more than one, the process will stuck at “Filter reads from fq_files based on hash table with xx thread”. I also received similar feedback from others. Hope it can be solved.
Platform: 13th Intel core processor with Windows 10 22H2

**Comment by plant720** [comment]
The Easy353 Windows GUI is developed using Python. However, Python's multiprocessing service on Windows computers uses the "spawn" mode. As a result, when using multiprocessing, all resources of a single process need to be copied, which puts a significant burden on the computer's memory and can also slow down the startup. Multiprocessing in the Easy353 Windows GUI is only convenient when processing small data and using fewer reference sequences.

**Comment by suLuyi** [comment]
Thanks for your reply. I will try the easy353 for Linux.
