### ISSUE TITLE
if reference sequence is amino acid

### ISSUE THREAD

**Issue by huang-baisha** [plant720/Easy353#6]
hello,
   I used fdog (https://github.com/BIONF/fDOG) to construct a reference sequence (amino acid sequence) based on which I would like to use easy353 to identify homologous genes in other species sequencing data. Does easy353 not recognize the reference sequence of the amino acid sequence? What should I do?

**Comment by plant720** [comment]
Thank you for reaching out. Unfortunately, Easy353 does not currently support using an amino acid sequence as a reference sequence. At the moment, there isn't a straightforward solution for this issue. You might need to explore alternative tools or approaches.
